# Generated by Django 3.2.9 on 2021-12-07 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TestForm',
        ),
        migrations.RemoveField(
            model_name='articlepost',
            name='status',
        ),
        migrations.AddField(
            model_name='petpost',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
    ]
