# Generated by Django 3.2.9 on 2021-12-08 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_auto_20211207_0007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petpost',
            name='age',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='petpost',
            name='color',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
