# Generated by Django 3.2.9 on 2021-12-08 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_auto_20211208_0502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currentevent',
            name='message',
            field=models.CharField(max_length=1000),
        ),
    ]
