# Generated by Django 3.2.9 on 2021-12-08 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0004_alter_currentevent_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adoptform',
            name='is_approved',
        ),
        migrations.RemoveField(
            model_name='fosterform',
            name='is_approved',
        ),
        migrations.RemoveField(
            model_name='volunteerform',
            name='is_approved',
        ),
        migrations.AddField(
            model_name='adoptform',
            name='status',
            field=models.CharField(choices=[('approved', 'approved'), ('in_process', 'in process'), ('rejected', 'rejected')], default='in_process', max_length=20),
        ),
        migrations.AddField(
            model_name='fosterform',
            name='status',
            field=models.CharField(choices=[('approved', 'approved'), ('in_process', 'in process'), ('rejected', 'rejected')], default='in_process', max_length=20),
        ),
        migrations.AddField(
            model_name='volunteerform',
            name='status',
            field=models.CharField(choices=[('approved', 'approved'), ('in_process', 'in process'), ('rejected', 'rejected')], default='in_process', max_length=20),
        ),
    ]
