# Generated by Django 3.2.9 on 2021-12-09 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0005_auto_20211208_2031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currentevent',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
