# Generated by Django 3.2.9 on 2021-12-16 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0007_articlepost_content_image_third'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlepost',
            name='caption_third',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
