# Generated by Django 3.2.9 on 2021-12-16 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0008_articlepost_caption_third'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlepost',
            name='url1',
            field=models.URLField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='articlepost',
            name='url2',
            field=models.URLField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='articlepost',
            name='url3',
            field=models.URLField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='articlepost',
            name='url4',
            field=models.URLField(blank=True, max_length=250, null=True),
        ),
    ]
