# Generated by Django 3.2.9 on 2021-12-19 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0009_auto_20211216_1052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlepost',
            name='caption',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='articlepost',
            name='caption_second',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='articlepost',
            name='caption_third',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
