# Generated by Django 3.2.9 on 2021-12-20 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0011_auto_20211219_2357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlepost',
            name='category',
            field=models.CharField(blank=True, choices=[('information', 'information'), ('news', 'news'), ('event', 'event'), ('seasonal', 'seasonal')], default='', max_length=20, null=True),
        ),
    ]
