# Generated by Django 3.2.9 on 2021-12-20 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0012_alter_articlepost_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='fosterform',
            name='question16',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='articlepost',
            name='category',
            field=models.CharField(blank=True, choices=[('information', 'information'), ('news', 'news'), ('event', 'event'), ('seasonal', 'seasonal')], max_length=20, null=True),
        ),
    ]
