# Generated by Django 3.2.10 on 2021-12-30 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0013_auto_20211220_0648'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articlepost',
            name='caption_third',
        ),
        migrations.RemoveField(
            model_name='articlepost',
            name='content_image_third',
        ),
    ]
