# Generated by Django 3.2.10 on 2022-01-18 02:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0015_alter_petpost_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articlepost',
            options={'ordering': ['created_on']},
        ),
    ]
