# Generated by Django 3.2.10 on 2022-01-18 03:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0016_alter_articlepost_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articlepost',
            options={'ordering': ['-created_on']},
        ),
    ]
